INSERT INTO author(name)
VALUES ('Jeramy Borer'),
       ('Bruno Heaney'),
       ('Velda Hegmann IV'),
       ('Sara Kuhn'),
       ('Yong Cummerata Jr.'),
       ('Felipe Pfannerstill'),
       ('Lorinda Muller'),
       ('Donovan Davis I'),
       ('Ms. Margarete Gerlach'),
       ('Herschel Simonis'),
       ('Alaina Rutherford'),
       ('Garret Friesen'),
       ('Bradly Rath I'),
       ('Randolph McDermott'),
       ('Delmer Watsica'),
       ('Gwenn Deckow V'),
       ('Noah Johnson'),
       ('Fletcher Rutherford IV'),
       ('Roscoe Schuppe'),
       ('Mrs. Natalya Jacobs'),
       ('Mrs. Barrett Pfeffer'),
       ('Sterling Zulauf'),
       ('Mr. Mohammed Hand'),
       ('Kirk Dach'),
       ('Miss Tad Reichel'),
       ('Rory Gerhold'),
       ('Alysa Bernhard'),
       ('Miss Boyce Erdman'),
       ('Jada Mills'),
       ('Cruz Herman'),
       ('Len Hudson II'),
       ('Bryon Rau'),
       ('Mr. Lashaun Schultz'),
       ('Major Robel'),
       ('Dorothea Kuphal'),
       ('Kendal Schamberger'),
       ('Chauncey Lowe Jr.'),
       ('Trudie Hirthe'),
       ('Mr. Sang Aufderhar'),
       ('Mohamed Funk'),
       ('Allan Lind'),
       ('Floyd Moore'),
       ('Earnest Block'),
       ('Kermit Bashirian'),
       ('Valentin Corwin'),
       ('Florida Jacobi'),
       ('Jay Marvin'),
       ('Mrs. Alecia Berge'),
       ('Clarence Wunsch'),
       ('Beau Romaguera'),
       ('Shalon Lebsack'),
       ('Walker Wisoky'),
       ('Howard Welch'),
       ('Mr. Howard Schroeder'),
       ('Erick Leannon'),
       ('Clarisa Heidenreich'),
       ('Jeremy Schultz'),
       ('Landon Frami Jr.'),
       ('Tifany Sawayn'),
       ('Sylvester Ullrich'),
       ('Mr. Leonila Harvey'),
       ('Lou Hane Sr.'),
       ('Ashlie Sipes DVM'),
       ('Dr. Craig Marvin'),
       ('Ambrose Stokes III'),
       ('Miss Leisa Wisoky'),
       ('Mr. Carmelo Murray'),
       ('Israel Fisher III'),
       ('Delmer Prohaska'),
       ('Franklyn Hartmann'),
       ('Chong Crona V'),
       ('Rana Beier'),
       ('Galen Ratke'),
       ('Hal Pacocha DDS'),
       ('Miss Noel Huel'),
       ('Mrs. Darnell Durgan'),
       ('Gordon Heaney'),
       ('Jillian Lueilwitz Jr.'),
       ('Gary Morissette DVM'),
       ('Jerald Paucek'),
       ('Ms. Cinda Dietrich'),
       ('Arnulfo Miller'),
       ('Shiela Jenkins'),
       ('Danyell Gislason'),
       ('Miss Manda Leuschke'),
       ('Ty Kshlerin'),
       ('Jarvis Kutch'),
       ('Federico Spencer'),
       ('Shon Treutel'),
       ('Marion Bartoletti Jr.'),
       ('Valentina Altenwerth'),
       ('Nelia Bashirian'),
       ('Carrol Towne DDS'),
       ('Dr. Jessie Macejkovic'),
       ('Mrs. Lizzie Wiza'),
       ('Marsha Kohler'),
       ('Mose Gulgowski'),
       ('Dorian Gutkowski'),
       ('Mrs. Bryon Botsford'),
       ('Eugenio Kohler')