server:
  port: 8080
spring.jpa:
  database: POSTGRESQL
  hibernate.ddl-auto: validate
  show-sql: true

spring.datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/excel
  username: postgres
  password: postgres
