version: '3.7'
services:
  dvd-rental-postgres:
    hostname: postgres
    image: postgres
    volumes:
      - ./postgres:/data/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dvd-user
      POSTGRES_PASSWORD: dvd-password
      POSTGRES_DB: dvd-rental
