INSERT INTO admin_code(code) VALUES ('M'),
                                    ('C'),
                                    ('T'),
                                    ('X'),
                                    ('M'),
                                    ('X'),
                                    ('T'),
                                    ('M'),
                                    ('C'),
                                    ('T'),
                                    ('X'),
                                    ('M');