server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:file:~/crudDB'
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /adminH2
