server:
  port: 8081
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        format_sql: true
    database: postgresql

  datasource:
    url: jdbc:postgresql://localhost:5432/dvd-rental
    username: postgres
    password: postgres
    type: com.zaxxer.hikari.HikariDataSource
